python make_fasta.py \
       -ref_fasta /mnt/data/male.hg19.fa \
       -chrom_sizes /mnt/data/annotations/by_release/hg19/hg19.chrom.sizes \
       -prefix /oak/stanford/groups/akundaje/projects/GECCO/FloraSNPs_FIGI_full_variant_list/FIGI_full_variant_list_chr \
       -chrom 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 \
       -suffix .txt.gz \
       -chrom_col Chr \
       -pos1_col Pos \
       -name_col id \
       -out_prefix FloraSNPs \
       -ref_allele_col REF \
       -alt_allele_col ALT \
       --flank 500 
