#with Peter's data 
#zcat /srv1/scratch/media/gecco/260N.overlap.filt.narrowPeak.hammock.gz /srv1/scratch/media/gecco/389N.overlap.filt.narrowPeak.hammock.gz /srv1/scratch/media/gecco/391N.overlap.filt.narrowPeak.hammock.gz /srv1/scratch/media/gecco/402N.overlap.filt.narrowPeak.hammock.gz /srv1/scratch/media/gecco/4925.overlap.filt.narrowPeak.hammock.gz /srv1/scratch/media/gecco/505N.overlap.filt.narrowPeak.hammock.gz  /srv1/scratch/media/gecco/626.overlap.filt.narrowPeak.hammock.gz /srv1/scratch/media/gecco/644N.overlap.filt.narrowPeak.hammock.gz /srv1/scratch/media/gecco/175N.overlap.filt.narrowPeak.hammock.gz /srv1/scratch/media/gecco/176N.overlap.filt.narrowPeak.hammock.gz /srv1/scratch/media/gecco/235N.overlap.filt.narrowPeak.hammock.gz /srv1/scratch/media/gecco/C37_H3K27ac.nodup.tagAlign_x_C37_Input.nodup.tagAlign.naive_overlap.narrowPeak.hammock.gz /srv1/scratch/media/gecco/Crypt5_H3K27ac.nodup.tagAlign_x_Crypt5_Input.nodup.tagAlign.naive_overlap.narrowPeak.hammock.gz /srv1/scratch/media/gecco/858N.overlap.filt.narrowPeak.hammock.gz /srv1/scratch/media/gecco/C28_H3K27ac.nodup.tagAlign_x_C28_Input.nodup.tagAlign.naive_overlap.narrowPeak.hammock.gz /srv1/scratch/media/gecco/C29_H3K27ac.nodup.tagAlign_x_C29_Input.nodup.tagAlign.naive_overlap.narrowPeak.hammock.gz /srv1/scratch/media/gecco/755N.overlap.filt.narrowPeak.hammock.gz /srv1/scratch/media/gecco/747N.overlap.filt.narrowPeak.hammock.gz /srv1/scratch/media/gecco/704N.overlap.filt.narrowPeak.hammock.gz /srv1/scratch/media/gecco/703N.overlap.filt.narrowPeak.hammock.gz /srv1/scratch/media/gecco/697N.overlap.filt.narrowPeak.hammock.gz /srv1/scratch/media/gecco/651N.overlap.filt.narrowPeak.hammock.gz | bedtools sort -i - | bedtools merge -i - > control.h3k27ac.bed

#without Peter's data 
#zcat  /srv1/scratch/media/gecco/C37_H3K27ac.nodup.tagAlign_x_C37_Input.nodup.tagAlign.naive_overlap.narrowPeak.hammock.gz /srv1/scratch/media/gecco/Crypt5_H3K27ac.nodup.tagAlign_x_Crypt5_Input.nodup.tagAlign.naive_overlap.narrowPeak.hammock.gz /srv1/scratch/media/gecco/858N.overlap.filt.narrowPeak.hammock.gz /srv1/scratch/media/gecco/C28_H3K27ac.nodup.tagAlign_x_C28_Input.nodup.tagAlign.naive_overlap.narrowPeak.hammock.gz /srv1/scratch/media/gecco/C29_H3K27ac.nodup.tagAlign_x_C29_Input.nodup.tagAlign.naive_overlap.narrowPeak.hammock.gz | bedtools sort -i - | bedtools merge -i - > control.h3k27ac.bed

#unmerged
zcat  /srv1/scratch/media/gecco/C37_H3K27ac.nodup.tagAlign_x_C37_Input.nodup.tagAlign.naive_overlap.narrowPeak.hammock.gz /srv1/scratch/media/gecco/Crypt5_H3K27ac.nodup.tagAlign_x_Crypt5_Input.nodup.tagAlign.naive_overlap.narrowPeak.hammock.gz /srv1/scratch/media/gecco/858N.overlap.filt.narrowPeak.hammock.gz /srv1/scratch/media/gecco/C28_H3K27ac.nodup.tagAlign_x_C28_Input.nodup.tagAlign.naive_overlap.narrowPeak.hammock.gz /srv1/scratch/media/gecco/C29_H3K27ac.nodup.tagAlign_x_C29_Input.nodup.tagAlign.naive_overlap.narrowPeak.hammock.gz | bedtools sort -i - |uniq > control.h3k27ac.unmerged.bed
bgzip control.h3k27ac.unmerged.bed
tabix -p bed control.h3k27ac.unmerged.bed.gz

