#get the narrowPeak, tagAlign, fc bigwig, pval bigwig files generated by the pipeline

prefix=/oak/stanford/groups/akundaje/projects/GECCO/scacheri_46_h3k27ac_chipseq/output_hg19

#narrowPeaks 
#find $prefix  -wholename "*call-reproducibility_overlap/execution/optimal_peak.narrowPeak.gz" | grep -v "glob" | grep -v "duplicate"  &> outputs/narrowPeak.files.txt

#pooled tagAligns (one tagAlign per biological replicate) 
#find $prefix -wholename "*call-bam2ta/shard-0/execution/*.nodup.tagAlign.gz" | grep -v "glob" | grep -v "duplicate"  &> outputs/nodup.tagAlign.files.txt

#pooled fold change bigwig 
#find $prefix -wholename "*/call-macs2/shard-0/execution/*fc.signal.bigwig" | grep -v "glob" | grep -v "duplicate" &> outputs/nodup.fc.signal.bigwig 

#pooled pval bigwig 
#find $prefix -wholename "*/call-macs2/shard-0/execution/*.pval.signal.bigwig" | grep -v "glob" | grep -v "duplicate" &> outputs/nodup.pval.signal.bigwig

#qc reports
#find $prefix -wholename "*/call-qc_report/execution/qc.json" | grep -v "glob" | grep -v "duplicate" &>outputs/qc.json 

#qc html
#find $prefix -wholename "*/call-qc_report/execution/qc.html" | grep -v "glob" | grep -v "duplicate" &>outputs/qc.html 


#if there are multiple entries for a given file, filter by timestamp 
python filter_by_timestamp.py --dir_steps=10 --file_list outputs/narrowPeak.files.txt --outf outputs/narrowPeak.files.txt.filtered 
python filter_by_timestamp.py --dir_steps=10 --file_list outputs/nodup.tagAlign.files.txt --outf outputs/nodup.tagAlign.files.txt.filtered 
python filter_by_timestamp.py --dir_steps=10 --file_list outputs/nodup.fc.signal.bigwig --outf outputs/nodup.fc.signal.bigwig.filtered
python filter_by_timestamp.py --dir_steps=10 --file_list outputs/nodup.pval.signal.bigwig --outf outputs/nodup.pval.signal.bigwig.filtered
python filter_by_timestamp.py --dir_steps=10 --file_list outputs/qc.json --outf outputs/qc.json.filtered
python filter_by_timestamp.py --dir_steps=10 --file_list outputs/qc.html --outf outputs/qc.html.filtered




#get any failed runs 
#./get_failed_runs.sh 
